---
apiVersion: v1
kind: Secret
metadata:
  name: c-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/skraft-redhat-backend-gitops
